export type Project = {
  id: number
  name: string
  status: "Active" | "Completed" | "Draft"
  entries: number
  judges: number
  track: string // Track name (e.g., "General", "Uber Track", "RBC Track")
}

export const defaultProjects: Project[] = [
  { id: 1, name: "AI Healthcare Assistant", status: "Active", entries: 15, judges: 3, track: "General" },
  { id: 2, name: "Sustainable Energy Platform", status: "Active", entries: 8, judges: 2, track: "General" },
  { id: 3, name: "Blockchain Voting System", status: "Completed", entries: 12, judges: 4, track: "General" },
  { id: 4, name: "Smart City IoT Network", status: "Draft", entries: 0, judges: 0, track: "General" },
  { id: 5, name: "Virtual Reality Education", status: "Active", entries: 22, judges: 3, track: "General" },
  { id: 6, name: "Climate Change Tracker", status: "Active", entries: 18, judges: 2, track: "General" },
  { id: 7, name: "FinTech Mobile App", status: "Active", entries: 14, judges: 3, track: "General" },
  { id: 8, name: "Autonomous Delivery Drones", status: "Active", entries: 9, judges: 2, track: "General" },
  { id: 9, name: "Mental Health Platform", status: "Active", entries: 25, judges: 4, track: "General" },
  { id: 10, name: "E-Commerce Analytics Tool", status: "Active", entries: 11, judges: 2, track: "General" },
  { id: 11, name: "Renewable Energy Dashboard", status: "Active", entries: 16, judges: 3, track: "General" },
  { id: 12, name: "Social Media Moderation AI", status: "Active", entries: 13, judges: 2, track: "General" },
  { id: 13, name: "Smart Home Automation", status: "Active", entries: 19, judges: 3, track: "General" },
  { id: 14, name: "Food Waste Reduction App", status: "Active", entries: 7, judges: 2, track: "General" },
  { id: 15, name: "Cybersecurity Training Platform", status: "Active", entries: 20, judges: 3, track: "General" },
  { id: 16, name: "Telemedicine Solution", status: "Active", entries: 17, judges: 3, track: "General" },
  { id: 17, name: "Supply Chain Optimizer", status: "Active", entries: 10, judges: 2, track: "General" },
  { id: 18, name: "Language Learning AI", status: "Active", entries: 24, judges: 4, track: "General" },
  { id: 19, name: "Carbon Footprint Calculator", status: "Active", entries: 6, judges: 2, track: "General" },
  { id: 20, name: "Job Matching Platform", status: "Active", entries: 21, judges: 3, track: "General" },
  { id: 21, name: "AR Shopping Experience", status: "Active", entries: 12, judges: 2, track: "General" },
  { id: 22, name: "Disaster Response System", status: "Active", entries: 15, judges: 3, track: "General" },
  { id: 23, name: "Personal Finance Manager", status: "Active", entries: 18, judges: 3, track: "General" },
  { id: 24, name: "E-Learning Platform", status: "Active", entries: 23, judges: 4, track: "General" },
  { id: 25, name: "Smart Agriculture System", status: "Active", entries: 8, judges: 2, track: "General" },
  { id: 26, name: "Community Engagement App", status: "Active", entries: 14, judges: 2, track: "General" },
  { id: 27, name: "Fitness Tracking Platform", status: "Active", entries: 16, judges: 3, track: "General" },
  { id: 28, name: "Event Management System", status: "Active", entries: 11, judges: 2, track: "General" },
  { id: 29, name: "Real Estate Analytics", status: "Active", entries: 9, judges: 2, track: "General" },
  { id: 30, name: "Music Discovery Platform", status: "Active", entries: 13, judges: 2, track: "General" },
  { id: 31, name: "Travel Planning Assistant", status: "Active", entries: 17, judges: 3, track: "General" },
  { id: 32, name: "Pet Care Management", status: "Active", entries: 5, judges: 2, track: "General" },
  { id: 33, name: "Legal Document Automation", status: "Active", entries: 19, judges: 3, track: "General" },
  { id: 34, name: "Content Creation Tool", status: "Active", entries: 22, judges: 4, track: "General" },
  { id: 35, name: "Parking Space Finder", status: "Active", entries: 7, judges: 2, track: "General" },
  { id: 36, name: "Recipe Sharing Platform", status: "Active", entries: 10, judges: 2, track: "General" },
  { id: 37, name: "Local Business Directory", status: "Active", entries: 12, judges: 2, track: "General" },
  { id: 38, name: "Study Group Organizer", status: "Active", entries: 15, judges: 3, track: "General" },
  { id: 39, name: "Crowdfunding Platform", status: "Active", entries: 20, judges: 3, track: "General" },
  { id: 40, name: "Task Management System", status: "Active", entries: 18, judges: 3, track: "General" },
  { id: 41, name: "Weather Prediction AI", status: "Active", entries: 14, judges: 2, track: "General" },
  { id: 42, name: "Online Marketplace", status: "Active", entries: 21, judges: 3, track: "General" },
  { id: 43, name: "News Aggregator", status: "Active", entries: 16, judges: 3, track: "General" },
  { id: 44, name: "Video Streaming Platform", status: "Active", entries: 25, judges: 4, track: "General" },
  { id: 45, name: "Productivity Suite", status: "Active", entries: 19, judges: 3, track: "General" },
  { id: 46, name: "Gaming Community Hub", status: "Active", entries: 11, judges: 2, track: "General" },
  { id: 47, name: "Fashion Styling App", status: "Active", entries: 8, judges: 2, track: "General" },
  { id: 48, name: "Investment Portfolio Tracker", status: "Active", entries: 13, judges: 2, track: "General" },
  { id: 49, name: "Home Renovation Planner", status: "Active", entries: 9, judges: 2, track: "General" },
  { id: 50, name: "Social Networking Platform", status: "Active", entries: 26, judges: 4, track: "General" },
]
