CREATE TABLE "hacker_schedule" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"day" text NOT NULL,
	"date_label" text NOT NULL,
	"time" text NOT NULL,
	"event_key" text NOT NULL,
	"title" text NOT NULL,
	"location" text DEFAULT '' NOT NULL,
	"day_order" integer NOT NULL,
	"time_order" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "hacker_schedule_day_time_event_unique" UNIQUE("day","date_label","time","event_key")
);
--> statement-breakpoint
CREATE INDEX "hacker_schedule_display_order_idx" ON "hacker_schedule" USING btree ("day_order","time_order","event_key");--> statement-breakpoint
INSERT INTO "hacker_schedule"
  ("day", "date_label", "time", "event_key", "title", "location", "day_order", "time_order")
VALUES
  ('Friday', 'December 21st', '5:00 PM', 'main', 'Check-in opens', 'Main Lobby', 0, 1020),
  ('Friday', 'December 21st', '5:00 PM', 'sponsorBooth', 'Sponsor fair', 'Atrium', 0, 1020),
  ('Friday', 'December 21st', '5:30 PM', 'main', 'Check-in opens', 'Main Lobby', 0, 1050),
  ('Friday', 'December 21st', '5:30 PM', 'sponsorBooth', 'Sponsor fair', 'Atrium', 0, 1050),
  ('Friday', 'December 21st', '6:00 PM', 'main', 'Check-in opens', 'Main Lobby', 0, 1080),
  ('Friday', 'December 21st', '6:00 PM', 'other', 'Help desk open', 'Info Booth', 0, 1080),
  ('Friday', 'December 21st', '7:00 PM', 'main', 'Opening ceremony', 'Auditorium', 0, 1140),
  ('Friday', 'December 21st', '7:30 PM', 'main', 'Opening ceremony', 'Auditorium', 0, 1170),
  ('Friday', 'December 21st', '8:30 PM', 'activities1', 'Team formation', 'Room 101', 0, 1230),
  ('Friday', 'December 21st', '8:30 PM', 'food', 'Dinner', 'Dining Hall', 0, 1230),
  ('Friday', 'December 21st', '9:00 PM', 'activities1', 'Team formation', 'Room 101', 0, 1260),
  ('Friday', 'December 21st', '10:00 PM', 'sponsorWorkshop', 'Build with APIs', 'Room 208', 0, 1320),
  ('Friday', 'December 21st', '10:00 PM', 'otherWorkshop', 'Project planning sprint', 'Room 204', 0, 1320),
  ('Saturday', 'December 22nd', '9:00 AM', 'main', 'Hacking continues', 'Hacker Space', 1, 540),
  ('Saturday', 'December 22nd', '9:00 AM', 'food', 'Breakfast', 'Dining Hall', 1, 540),
  ('Saturday', 'December 22nd', '9:30 AM', 'main', 'Hacking continues', 'Hacker Space', 1, 570),
  ('Saturday', 'December 22nd', '10:00 AM', 'main', 'Hacking continues', 'Hacker Space', 1, 600),
  ('Saturday', 'December 22nd', '10:00 AM', 'sponsorWorkshop', 'AI product workshop', 'Room 208', 1, 600),
  ('Saturday', 'December 22nd', '10:00 AM', 'otherWorkshop', 'Design systems crash course', 'Room 206', 1, 600),
  ('Saturday', 'December 22nd', '10:30 AM', 'main', 'Hacking continues', 'Hacker Space', 1, 630),
  ('Saturday', 'December 22nd', '10:30 AM', 'sponsorWorkshop', 'AI product workshop', 'Room 208', 1, 630),
  ('Saturday', 'December 22nd', '10:30 AM', 'otherWorkshop', 'Design systems crash course', 'Room 206', 1, 630),
  ('Saturday', 'December 22nd', '12:00 PM', 'food', 'Lunch', 'Dining Hall', 1, 720),
  ('Saturday', 'December 22nd', '12:00 PM', 'sponsorBooth', 'Sponsor booth challenge', 'Atrium', 1, 720),
  ('Saturday', 'December 22nd', '1:00 PM', 'activities1', 'Mini games', 'Atrium', 1, 780),
  ('Saturday', 'December 22nd', '1:00 PM', 'sponsorBooth', 'Sponsor booth challenge', 'Atrium', 1, 780),
  ('Saturday', 'December 22nd', '6:00 PM', 'food', 'Dinner', 'Dining Hall', 1, 1080),
  ('Saturday', 'December 22nd', '6:00 PM', 'other', 'Mentor office hours', 'Help Desk', 1, 1080),
  ('Saturday', 'December 22nd', '11:30 PM', 'main', 'Project submission deadline', 'Online', 1, 1410),
  ('Sunday', 'December 23rd', '9:00 AM', 'food', 'Breakfast', 'Dining Hall', 2, 540),
  ('Sunday', 'December 23rd', '9:00 AM', 'judging', 'Judging begins', 'Expo Floor', 2, 540),
  ('Sunday', 'December 23rd', '9:30 AM', 'judging', 'Judging begins', 'Expo Floor', 2, 570),
  ('Sunday', 'December 23rd', '11:00 AM', 'judging', 'Final demos', 'Auditorium', 2, 660),
  ('Sunday', 'December 23rd', '11:00 AM', 'sponsorBooth', 'Sponsor expo', 'Atrium', 2, 660),
  ('Sunday', 'December 23rd', '12:30 PM', 'food', 'Lunch', 'Dining Hall', 2, 750),
  ('Sunday', 'December 23rd', '12:30 PM', 'judging', 'Final demos', 'Auditorium', 2, 750),
  ('Sunday', 'December 23rd', '3:00 PM', 'main', 'Closing ceremony', 'Auditorium', 2, 900);
